FROM fluent/fluentd:v1.17.0-debian-amd64-1.0
USER root
RUN apt-get update
    
RUN apt-get install -y iproute2

RUN gem update fluentd

ENV DEBIAN_FRONTEND=noninteractive

RUN ln -fs /usr/share/zoneinfo/Europe/Madrid /etc/localtime && \
    echo "Europe/Madrid" > /etc/timezone && \
    apt-get update && \
    apt-get install -y tzdata && \
    dpkg-reconfigure --frontend noninteractive tzdata

COPY /ep_fluentd.sh /ep_fluentd.sh
RUN chmod +x /ep_fluentd.sh