# fluentd/Dockerfile

FROM fluent/fluentd:v1.12-1
USER root
RUN ["gem",  "install", "multi_json",  "-v",  "1.15.0"]
RUN ["gem",  "install", "faraday-net_http",  "-v",  "3.0.2"]
RUN ["gem",  "install", "faraday",  "-v",  "2.8.1"]
RUN ["gem",  "install", "excon",  "-v",  "1.2.5"]
RUN ["gem", "install", "fluent-plugin-elasticsearch", "--no-document", "--version", "5.0.3"]

COPY ep_fluentd.sh /ep_fluentd.sh

RUN chmod +x /ep_fluentd.sh