apiVersion: v1
kind: Pod
metadata:
  name: host4
  labels:
    rol: host
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [ 
        {
          "name": "bridge-rb-h4",
          "interface": "eth1",
          "ips": ["10.0.4.2/24"],
          "gateway": "10.0.4.1"
        }
      ]
spec:
  containers:
    - name: host4
      image: python:3.6-alpine
      command: ["/bin/sh", "-c"]
      args:
        - |
          ip route del default
          ip route add default via 10.0.4.1 dev eth1
          sleep infinity
      securityContext:
        privileged: true
        capabilities:
          add:
          - NET_ADMIN 