apiVersion: v1
kind: Pod
metadata:
  name: rb
  labels:
    rol: router
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [ 
        {
          "name": "bridge-rc2-rb",
          "interface": "eth1",
          "ips": ["10.3.0.2/30"]
        },
        {
          "name": "bridge-rb-h3",
          "interface": "eth2",
          "ips": ["10.0.3.1/24"]
        },
        {
          "name": "bridge-rb-h4",
          "interface": "eth3",
          "ips": ["10.0.4.1/24"]
        }
      ]
spec:
  containers:
    - name: rb
      image: python:3.6-alpine
      command: ["/bin/sh", "-c"]
      args:
        - |
          sysctl -w net.ipv4.ip_forward=1;
          iptables -F FORWARD;
          iptables -P FORWARD ACCEPT;
          iptables -A FORWARD -j ACCEPT;

          ip route add 10.0.1.0/24 via 10.3.0.1;
          ip route add 10.0.2.0/24 via 10.3.0.1;

          ip route add 10.100.0.0/24 via 10.3.0.1;

          sleep infinity;
      securityContext:
        privileged: true
        capabilities:
          add:
          - NET_ADMIN 