apiVersion: v1
kind: Pod
metadata:
  name: rc2
  labels:
    rol: router
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [ 
        {
          "name": "bridge-rc1-rc2",
          "interface": "eth1",
          "ips": ["10.1.0.2/30"]
        },
        {
          "name": "bridge-rc2-ra",
          "interface": "eth2",
          "ips": ["10.2.0.1/30"]
        },
        {
          "name": "bridge-rc2-rb",
          "interface": "eth3",
          "ips": ["10.3.0.1/30"]
        }
      ]
spec:
  containers:
    - name: rc2
      image: python:3.6-alpine
      command: ["/bin/sh", "-c"]
      args:
        - |
          sysctl -w net.ipv4.ip_forward=1;

          for i in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 0 > $i; done

          iptables -F FORWARD;
          iptables -P FORWARD ACCEPT;
          iptables -A FORWARD -j ACCEPT;

          ip route add 10.0.1.0/24 via 10.2.0.2;
          ip route add 10.0.2.0/24 via 10.2.0.2;
          ip route add 10.0.3.0/24 via 10.3.0.2;
          ip route add 10.0.4.0/24 via 10.3.0.2;

          ip route add 10.100.0.0/24 via 10.1.0.1;

          sleep infinity;
      securityContext:
        privileged: true
        capabilities:
          add:
          - NET_ADMIN 