apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    rol: server
    app: hello-world
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [ 
        {
          "name": "bridge-serv-rc1",
          "interface": "eth1",
          "ips": ["10.100.0.10/24"]
        }
      ]
spec:
  containers:
    - name: server
      image: python:3.6-alpine
      ports:
        - containerPort: 3000
      command: ["/bin/sh", "-c"]
      args:
        - |
          #Instalar paquetes
          apk update
          apk add --no-cache git nodejs npm
          
          if [ -d /agr ]; then rm -rf /agr; fi;
          git clone https://github.com/Hsabaterl/agr.git /agr;
          cd /agr; 
          npm install express;

          ip route del default
          ip route add default via 10.100.0.1 dev eth1;
          
          node app.js;
      securityContext:
        privileged: true
        capabilities:
          add:
          - NET_ADMIN 
