FROM ubuntu:22.04

RUN apt-get update && apt-get install -y iputils-ping && apt-get install -y iproute2 iptables
RUN apt-get update && apt-get install -y curl

RUN ln -fs /usr/share/zoneinfo/Europe/Madrid /etc/localtime && \
    echo "Europe/Madrid" > /etc/timezone && \
    apt-get update && \
    apt-get install -y tzdata && \
    dpkg-reconfigure --frontend noninteractive tzdata

COPY entrypoints/ep_client1.sh entrypoints/ep_client1.sh
COPY entrypoints/ep_client2.sh entrypoints/ep_client2.sh
COPY entrypoints/ep_client3.sh entrypoints/ep_client3.sh
COPY entrypoints/ep_client4.sh entrypoints/ep_client4.sh
RUN chmod +x /entrypoints/ep_client1.sh /entrypoints/ep_client2.sh /entrypoints/ep_client3.sh /entrypoints/ep_client4.sh

CMD ["/bin/bash"]