apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-ra-h1
  namespace: default
  labels:
    rol: bridge
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "red-ra-h1",
      "type": "bridge",
      "bridge": "bridge-ra-h1",
      "isGateway": false,
      "ipam": {
        "type": "static"
      }
    }
